### ISSUE TITLE
vuejs component

### ISSUE THREAD

**Issue by mailcomorg** [abagames/crisp-game-lib#10]
hi. can i use this lib in vuejs components?

**Comment by mailcomorg** [comment]
May I request that you apply these modifications?  I want to use this awesome library in my vue project.thank you so much.

**Comment by abagames** [comment]
I have no plans to modify the library for use with the component. You can fork and modify `view.ts` to add canvas as a child of the component.
https://github.com/abagames/crisp-game-lib/blob/master/src/view.ts

**Comment by mailcomorg** [comment]
Thank you 👍👍
