### ISSUE TITLE
Request: save high scores using local storage

### ISSUE THREAD

**Issue by gingerbeardman** [abagames/crisp-game-lib#14]
It would be great if the games could save high score using local storage

**Comment by gingerbeardman** [comment]
Arigatou gozaimasu!

**Comment by abagames** [comment]
I have no plans to do so at this time.
This is because I have added audio-related improvements in ver. 1.2, so I cannot simply update the library version of games that have already been published.

**Comment by gingerbeardman** [comment]
I see!
